# Generated by Django 4.0.3 on 2022-03-08 16:07

import config.utils
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^([A-Za-z0-9\\-\\_]+)', 'Incorrect format, please correct it below')], verbose_name='Name')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^([A-Z0-9\\-\\_]+)', 'Incorrect format, please correct it below')], verbose_name='Code')),
                ('picture', models.ImageField(upload_to=config.utils.directory_medication_picture, verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'tbl_medication',
            },
        ),
    ]
