# Generated by Django 3.2.12 on 2022-03-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='picture_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Picture Name'),
        ),
    ]
