# Generated by Django 4.0.3 on 2022-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(blank=True, null=True, through='drone.LoadingDrone', to='medication.medication'),
        ),
    ]
