# Generated by Django 4.0.3 on 2022-03-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_alter_drone_medications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='battery',
            new_name='battery_capacity',
        ),
    ]
