# Generated by Django 3.2.12 on 2022-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_auditdrone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serial',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serial'),
        ),
    ]
