# Generated by Django 3.2.12 on 2022-03-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0006_alter_drone_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='weight',
            new_name='weight_limit',
        ),
    ]
